### ISSUE TITLE
Data update

### ISSUE THREAD

**Issue by KennethEnevoldsen** [martbern/dfm-visualisation#10]
Thinking a table something like this (basically means in need the "Other group"): 
```
table 1:

                       Pronouns.      Names.          Religions
 source   tokens     Female  Male   Female   Male    Christianity   Islam  Other
 HopeTwitter  100     0.05% [0.01; 0.09]
 ...
 
caption: Due to the relatively low proportion of other religions they are combined in one group, including atheism, hinduism, buddhism.
```
 We will also need to fix the CI issue if it is fixable (one option is probably to add a very tiny amount of noise).
 
For the plots I see two plots of 3x4 column where we facet wrap on source and porn, neg, pos. Similar to the result tables. We will also need to fix the color to red blue for the religion plot.
 
- [ ] Add other group
- [x] Fix CI issue
- [ ] change color religion plots
- [ ] facet wrap w. porn, neg, pos 
- [ ] For clarity we should probably rerun the linear model using the model prop ~ 0 + (prop:gender)*source. This will make it such that there is no intercept (and the danews will become explicit)
- [ ] of possible the suggestive star for p = 0.1 (why is this a default!) - if not possible I will just remove it in post.

**Comment by MartinBernstorff** [comment]
Hahaha, Kenneth, de her sætninger er _meget_ upolerede og kræver en del arbejde at parse ;-)

Jeg tror jeg fanger, hvad du mener, men bekræfter lige inden jeg begynder på arbejdet:

**Tables:**
- [x] Aggregate "atheism, hinduism, buddhism" and other religions to an "other" group 
- [x] Add a tiny bit of noise so no CIs are NaN

**Models:**
- [x] For clarity we should probably rerun the linear model using the model prop ~ 0 + (prop:gender)*source. This will make it such that there is no intercept (and the danews will become explicit)
- [x] If possible, remove the suggestive star for p = 0.1 (why is this a default!)

**Plots:**

- [x] Make it so colors are the same across all religion plots
- [x] Facet wrap on source and outcome (porn, neg, pos.)


PS: GitHubs parsing af todos er godt nok helt i hegnet.

**Comment by MartinBernstorff** [comment]
Here you go!

[tables.zip](https://github.com/martbern/dfm-visualisation/files/8853580/tables.zip)
[plots.zip](https://github.com/martbern/dfm-visualisation/files/8853586/plots.zip)
