### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by KennethEnevoldsen** [martbern/dfm-visualisation#9]
- Number of tokens pr category

**Comment by martbern** [comment]
Which categories do you want this over? Exclusively source, or also "gendered docs" etc.?

**Comment by KennethEnevoldsen** [comment]
Number of tokens pr. source (e.g. danews)

**Comment by KennethEnevoldsen** [comment]
så det var de 10M basically

**Comment by martbern** [comment]
Du har lukket denne? Har du gjort det selv? :-)

**Comment by KennethEnevoldsen** [comment]
Yep du havde sendt informationen på slack.
